"""removed cover_image field

Revision ID: 5111ac125e88
Revises: 7fc7cea870d8
Create Date: 2026-05-15 10:50:26.833879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5111ac125e88'
down_revision: Union[str, Sequence[str], None] = '7fc7cea870d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
